### ISSUE TITLE
Defaulting to latest capsule version breaks development system 

### ISSUE THREAD

**Issue by MatthewJWalls** [chrischristo/capsule-maven-plugin#29]
Feel free to close this issue if you think this behavior should be correct, but I felt I should raise it to see what you thought:

About a week ago we were struck at work with a weird issue where our Jenkins CI (which emits Capsule'd jars) started generating Capsules that no longer functioned, complaining about:

    Error occurred during initialization of VM
    agent library failed to init: instrument
    Failed to find Premain-Class manifest attribute in ...

This really weirded us out because nothing had changed as far as we were aware; the libraries were the same, Jenkins was the same, and it wasn't the code at fault because if we built old versions of our software with Jenkins, it would still produce the error.

After a fair few rabbit holes I eventually realised that the new version of Capsule, *which was being automatically pulled by the maven plugin*, had started using the Java Instrumentation package, and the manifest now required "Premain-Class" to be set in the manifest in order to work properly. After modifying the pom, this resolved the issue. The whole thing took about a day and a half to diagnose.

edit:

I just noticed the "Now adds Premain-Class: Capsule to manifest by default." in version 0.10.7, we tried 0.10.8 to resolve this in our testing, but this did not work properly either, but I'm more interested in whether the idea of having the capsule version always the latest (unless you specify otherwise) as default is valid, considering breaking changes like this might happen in the future.

**Comment by chrischristo** [comment]
Hi, thanks for reporting this, and sincerest apologies that this occurred. It was the recent release of capsule that included this new requirement. I was under the impression that capsule would maintain backwards compatibility at least in the sense of what is required in the manifest. This is why I did it like so, and also since we were all generally in early development we were iterating fast so wanted to ensure the user would use the latest version of capsule (bugs were being fixed daily). Alas this now has proven a bad idea going forward. I think perhaps it's best to require that the user specify the capsule version to use in the plugin options so your issue wouldn't happen to anyone else.

Apologies again! Ps away at the moment so will look to get this done around oct5. Let me know of any other issues.

**Comment by MatthewJWalls** [comment]
A simple change I suppose would just be to alter the documentation/examples for the plugin configuration to introduce pinning the capsule version first, and then leave the fact that you can have it unpinned as a by-the-way. Up to you guys.

**Comment by chrischristo** [comment]
Ok, after some thought, I've decided thats its best that with each new release of the plugin, it will state the currently supported version of Capsule. So this will be listed in the top of the documentation, so for example, the upcoming version 1.0 of the plugin will support the v1.0 of capsule. In practice this means that the plugin has been tested against that version of Capsule, but of course you may use any version of Capsule whether newer or older, but at your own risk.

Also, if the version of Capsule is not specified in the pom properties (`<capsule.version>`), then instead of using the latest version of Capsule, it will use this predefined default/tested version (so from above, v1.0). Thus, this will mean that the plugin's state remains constant (unless you manually specify a different version of Capsule to use).

**Comment by chrischristo** [comment]
[Fixed in 1.0.0](https://github.com/chrischristo/capsule-maven-plugin/releases/tag/capsule-maven-plugin-1.0.0).
